name: Release

on: 
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Clear NuGets
      run: dotnet nuget locals all --clear
    - name: Pack
      run: dotnet pack --no-build --output . --configuration Release
    - name: Push NuGets
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}} *.nupkg
    - name: Publish - Windows
      if: github.ref == 'refs/heads/main'
      run: dotnet publish -c release -r win-x64 -f net5 -p:PublishSingleFile=true -p:PublishTrimmed=true
      working-directory: ./publish-runner
    - name: Upload
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@main
      with:
        name: mobius-ilasm-win-x64
        path: publish-runner/bin/release/net5/win-x64/publish
